### ISSUE TITLE
CMake cannot generate gitrevision.h when cgreen is git submodule

### ISSUE THREAD

**Issue by souryogurt** [cgreen-devs/cgreen#199]
It seams CMake cannot generate `gitrevision.h` when cgreen is included as git submodule.

## Steps to reproduce
1. Create empty repo `mkdir poc && cd poc && git init`
1. Add cgreen as submodule `git submodule add  https://github.com/cgreen-devs/cgreen.git`
1. Configure it `cd cgreen && cmake .`
1. Build `make`

## Actual Result
The `make` tool reports that there are no `.git/logs/HEAD`
```sh
make[2]: *** No rule to make target '.git/logs/HEAD', needed by 'gitrevision.h'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1122: src/CMakeFiles/cgreen_shared.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

## Expected result
Cgreen is built. 

## Additional info
Looks like when cgreen is included as a submodule, it doesn't contain real `.git` directory. Instead, it contains `.git` file that points to real cgreen's `.git` directory.

I know, it is not documented way to use cgreen, but it is really convenient in a CI environment.

**Comment by thoni56** [comment]
It would probably be possible extend the logic at the top of `src/CMakeLists.txt` to handle that case too.

**Comment by selavy** [comment]
I'm considering working on this; is there any technical reason to keep the minimum cmake version at 2.8.5? CMake 3.0+ is much cleaner/easier IMO, but don't want to put in the work of a refactor to modern cmake if there's a technical (or ideological) reason that prohibits it.

**Comment by thoni56** [comment]
Thanks for volunteering!

AFAIK there are no technical reasons. The reasoning was based on the fact that there where some environments where CMake was old. I don't have any recent experience with any of those environments, but I suppose one could possibly try to do an inventory of that to make an (somewhat) informed decision. @matthargett or possibly @gardenia might have some input here. At least some historic data point.

If that pans out to indicate that there is no obstacle then I suppose the move to 3.0 would be a first PR. And the fix on top of that.

**Comment by matthargett** [comment]
Bumping to whatever 3.x version is installable in latest Ubuntu LTS and RHEL is fine by me :)

**Comment by dmeehan1968** [comment]
Just ran into this same issue.  I'm running `cmake version 3.1.20141230-g3b62cb` on my system and using that to build cgreen, so there may not be much if any work to use a later cmake.

I'm not familiar with cmake, it seems that the find_file method ends up recursing up the git hierarchy until it reaches the root repo.  From the docs its not clear if its possible to limit this.  Happy to help with this if anyone can give pointers.

**Comment by selavy** [comment]
Was playing around with this today here: https://github.com/selavy/cgreen-submodule-test

I read the steps to reproduce too quickly initially, and @souryogurt is trying to build cgreen differently than what I was trying to do. I was trying to have cgreen as a submodule, which I will add with a `add_subdirectory()` call (see https://github.com/selavy/cgreen-submodule-test/blob/2742f5251b74709f03ea6f7c91eb311bcdda9bf5/CMakeLists.txt#L16)

* The current cmake will work correctly in this scenario, but 

1) It generates the gitrevision.h file in the top level directory (i.e. my project), which I'd consider a little strange. Luckily the fix for that is simple, switch the uses of CMAKE_SOURCE_DIR -> PROJECT_SOURCE_DIR here: https://github.com/cgreen-devs/cgreen/blob/669046702ade1e480e13c191ca2c19f0172c69c1/src/CMakeLists.txt#L7-L24  PROJECT_SOURCE_DIR points to the directory where the last call to project() was made, which is exactly what we want in this case.

2) The real issue that I was hitting is that CGREEN_LIBRARIES and CGREEN_INCLUDE_DIRS aren't set if you just do `add_subdirectory(cgreen)` (because they are set via the `find_package(cgreen)` call). The workaround is something like this: https://github.com/selavy/cgreen-submodule-test/blob/2742f5251b74709f03ea6f7c91eb311bcdda9bf5/CMakeLists.txt#L17 . However, it would be nice to create a CGreen target if the cmake version >= 3.0 so I can do the easier `target_link_libraries(MyApp CGreen)`.

* To fix @souryogurt 's use-case, I believe the correct solution is to use `git rev-parse` rather than looking for the .git directory.

```
execute_process(
    COMMAND git rev-parse --sq --absolute-git-dir
    OUTPUT_VARIABLE GITDIR
    WORKING_DIRECTORY "${CMAKE_PROJECT_DIR}"
    OUTPUT_STRIP_TRAILING_WHITESPACE
    )
```

My plan is:
1) I've first opened a PR to use PROJECT_SOURCE_DIR here: https://github.com/cgreen-devs/cgreen/pull/204
2) PR to use git rev-parse to find the .git directory
3) PR to add a cmake target if the cmake_version >= 3.0

**Comment by dmeehan1968** [comment]
@selavy Just wanted to confirm that the `execute_process` fix works for me.  I'm using `make` via Xcode's build system, not trying to integrate cgreen into a super-projects cmake.

**Comment by thoni56** [comment]
@selavy If I understand correctly, the PR that I just merged solves the actual problem this issue is describing, so that the `gitrevision.h` is now created in the correct place.

This means that we should close this issue, and make the other points in your list as "improvement PR:s", or if you want to make issues for them, that's fine but not necessary.

Don't forget to update the description of "Cgreen as a submodule" for your item 3.

**Comment by souryogurt** [comment]
@thoni56 I guess the PR that you merged didn't solve this issue. It can be resolved as explained by @selavy in point 3 by using `GITDIR` variable produced from `git rev-parse --sq --absolute-git-dir` instead of searching for hardcoded `.git` directory using `find_file`. 

I guess @selavy going to add the next PR that will fix this issue as described in his plan.

**Comment by thoni56** [comment]
I have no experience with sub-modules, I thought that there *was* a `.git` directory in the root of the sub-module, so that the second part was a generalization. But anyway, @selavy will probably clear that out ;-)

**Comment by dmeehan1968** [comment]
If I'm understanding this correctly, the problem has two parts:

1. Location of gitrevision.h - this should be a within the cgreen repo (not a parent/container), as it relates to the cgreen repos git HEAD.  The PR seems to address the relative location for this file.  This in itself seems a bit wonky, as if its a build product by convention, it should be stored in `build` by convention.  

2. Determination of location of cgreen git repo, @selavy 's point 2 and the execute_process fix.

In my usage, it seems that only the second part is necessary, as the gitrevision.h is correctly being written in the cgreen submodule directory.  Without part 2, the build fails because the submodule .git is a file not a folder, and need to be parsed to determine the actual location of .git/logs/HEAD relevant to the submodule state.

**Comment by thoni56** [comment]
Thanks @dmeehan1968, that was the part I was missing, that .`.git` is just a file for sub-modules.

Re: place of `gitrevision.h` - well, kind of. But since it is included by the source it will be harder (as in more un-natural) to find in the build directory, won't it? I'm willing to accept a PR for a nice solution.

**Comment by dmeehan1968** [comment]
> Re: place of `gitrevision.h` - well, kind of. But since it is included by the source it will be harder (as in more un-natural) to find in the build directory, won't it?

Aah, yes, I didn't spot that, and so yes, it would be better to have it at repo root.

**Comment by dmeehan1968** [comment]
FWIW, I've created a fork and branch equivalent to @selavy 's suggested execute_process (https://github.com/Wavetrend/cgreen/tree/git-submodule)

I'm happy to wait for @selavy to do their own PR as there maybe other stuff that needs checking, but this is what I'm now using for my submodule to fix my build.

**Comment by selavy** [comment]
@dmeehan1968 I'm confused by your PR, you shouldn't need find_file() call anymore (https://github.com/Wavetrend/cgreen/blob/eb31f51434d7136b940a7013aa61620b8723a454/src/CMakeLists.txt#L11).

Ran into a slight snag while testing this. The --absolute-git-dir option wasn't added until 2.13.2, and my Ubuntu 16.04 has git 2.7.4. I tried switching to --git-dir, and it works in all cases except when doing an in-source build (specially when cgreen is not a submodule). For some reason when --git-dir is called from a submodule it returns an absolute path, but otherwise it returns a relative one. I could fix this with readlink, but I don't know how to do that in a cross platform way.

So I'm still working on a solution, and I will keep you all in the loop.

**Comment by dmeehan1968** [comment]
@selavy it wasn’t intended as a PR and I merely copied your suggestion and it worked. I forked so that i could apply it to my project and it seems to to solve my problem. Thanks very much for that part of the solution. 

You may well be right in the find_file, I’m not conversant with cmake so done understand it’s purpose. I made a second change to move the execute_process before it as find_file seemed to reference GIT_DIR so that seemed relevant. 

I’m not integrating cmake into a cmake super project so some of these finer points don’t seem to affect me. As long as I can build cmake when it’s a git submodule I’ll be happy 😃

**Comment by selavy** [comment]
After much consternation, I believe https://github.com/cgreen-devs/cgreen/pull/206 will work across all of desired build configurations. 

I do not have access to a Windows or OS X compilation and cmake environment setup, could someone test this change? I'm most concerned about Windows testing because it looks like the current version of git via homebrew is 2.24, which should work.

* out-of-source test (most important): 

```
$ git clone https://github.com/selavy/cgreen.git
$ cd cgreen
$ git checkout origin/find-git-directory
$ mkdir build
$ cd build
$ cmake ..
$ make
```

* in-source test:

```
$ git clone https://github.com/selavy/cgreen.git
$ cd cgreen
$ git checkout origin/find-git-directory
$ cmake .
$ make
```

* submodule in-source test:

```
$ mkdir poc
$ cd poc
$ git init
$ git submodule add https://github.com/selavy/cgreen.git
$ cd cgreen
$ git checkout origin/find-git-directory
$ cmake .
$ make
```
